### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Arnold1** [carlos-jenkins/csv2vcd#1]
Hi,

is the time (for row2 and row3 of input.csv) defined as time between those two samples, the absolute time? why is there a negative time?

```
0,1,0,0,-52.430000 us
0,1,0,0,-52.428333 us
```

when i open the coverted vcd file with GTKWave and move the cursor to the left, i can see:

```
CLK=1
CS=0
DIN=0
DOUT=0
```

but the csv file shows the first sample with, why are csv and vcd different? CLK=0 and CS=1...

```
"CLK","CS","DOUT","DIN","Time"
0,1,0,0,-52.430000 us
```

Thanks,
A

**Comment by Arnold1** [comment]
thanks for your reply.
great, did you test your tool with some traces?
do you know any other tools to visualize vcd besides GTKWave?
do you know a tool which converts vcd into a csv?

**Comment by Arnold1** [comment]
ok.

how can you convert a csv file with analog signals (float instead int) to vcd?
i get this error:

```
Breakpoint at line #1.
Traceback (most recent call last):
  File "csv2vcd", line 207, in <module>
    main()
  File "csv2vcd", line 201, in main
    if not convert(module, infile, outfile):
  File "csv2vcd", line 133, in convert
    tinit, pinit = get_parts(l)
  File "csv2vcd", line 94, in get_parts
    cparts = [int(p) for p in parts]
ValueError: invalid literal for int() with base 10: '0.000000'
```

i think line 94 should be replaced with, in case of a float?

```
cparts = [float(p) for p in parts]
```

**Comment by Arnold1** [comment]
my csv looks like that:

```
0.0,1.5,0.6,2.3,-52.415000 us
```

can you support that?

**Comment by Arnold1** [comment]
by floats i mean analog signals.
great, let me test if that works.

**Comment by mohankotgire** [comment]
Hello Mr. Carlos Jenkins,

I tried to convert real data csv file to vcd with your scripts, but unfortunately, it's not successful. I could see the generated vcd files contains some random variable names (not the same in CSV file). I am also attaching the csv file for your reference. Could you please help me resolve the issue (I am attaching the respective *xls file here)?

[Book1.xlsx](https://github.com/carlos-jenkins/csv2vcd/files/1985911/Book1.xlsx)

Thanks in advance!
Regards,
Mohan
